-- ============================================================
-- Phase 2 — PAID resources: private storage + purchase records.
-- Paste ALL of this into Supabase → SQL Editor → New query → Run.
-- Safe to re-run.
--
-- Paid files must NEVER be publicly downloadable, or people could grab the
-- URL and skip paying. So they live in a PRIVATE bucket and are only reachable
-- via short-lived signed URLs generated by the verify-payment function AFTER a
-- payment is verified.
-- ============================================================

-- 1) resources gets a column for the private file's storage path
alter table resources add column if not exists file_path text;

-- 2) private bucket for paid files (public = false)
insert into storage.buckets (id, name, public)
values ('paid-resources', 'paid-resources', false)
on conflict (id) do update set public = false;

-- Files: only logged-in owner (admin) can upload/manage. There is deliberately
-- NO public read policy — anon visitors cannot list or download these directly.
drop policy if exists "auth manage paid" on storage.objects;
create policy "auth manage paid" on storage.objects
  for all to authenticated
  using (bucket_id = 'paid-resources')
  with check (bucket_id = 'paid-resources');

-- 3) purchase log — who bought what. Written only by the Edge Function
--    (service role bypasses RLS); no public/anon access at all.
create table if not exists purchases (
  id                  bigint generated always as identity primary key,
  resource_id         bigint references resources(id) on delete set null,
  email               text,
  name                text,
  amount              numeric,
  currency            text,
  razorpay_order_id   text,
  razorpay_payment_id text,
  created_at          timestamptz default now()
);
alter table purchases enable row level security;
-- (no policies added → anon/public cannot read or write; only the service
--  role inside the Edge Function can, because it bypasses RLS)
